CREATE TABLE USER (
   USER_ID CHAR(15) PRIMARY KEY,
   USER_PW CHAR(20),
   USER_EMAIL CHAR(30),
   MOB_NO INT(12),
   CRT_DTM DATETIME
);

CREATE TABLE REST (
  REST_ID INT(10) PRIMARY KEY,
  REST_NM CHAR(20),
  FOOD_CATE CHAR(10),
  LAT_CDNT DECIMAL(15,12),
  LNG_CDNT DECIMAL(15,12),
  CRT_DTM DATETIME
 );

CREATE TABLE GROUP_INFO (
  GROUP_ID INT(8) auto_increment PRIMARY KEY,
  CRT_USER_ID CHAR(15),
  GROUP_NM CHAR(20),
  CRT_DTM DATETIME
 );

CREATE TABLE GROUP_MEMBER (
  GROUP_ID INT(8),
  USER_ID CHAR(15),
  CONSTRAINT GROUP_MEMBER_PK PRIMARY KEY(GROUP_ID, USER_ID)
);

CREATE TABLE GROUP_REST (
  GROUP_ID INT(8),
  REST_ID INT(10),
  CRT_DTM DATETIME,
  CONSTRAINT GROUP_REST_PK PRIMARY KEY(GROUP_ID, REST_ID)
 );

CREATE TABLE GROUP_INVITE (
  INVITE_ID INT(8) auto_increment PRIMARY KEY,
  GROUP_ID INT(8),
  SEND_USER_ID CHAR(15),
  RECV_USER_ID CHAR(15),
  RES_STATUS CHAR(5),
  CRT_DTM DATETIME,
  RES_DTM DATETIME
 );